### ISSUE TITLE
Use a code formatter eg. pretteir to format the code

### ISSUE THREAD

**Issue by ajay47** [vikasjangir202/Vehicle-Parking-Webpage#2]
For example use space around both sides of = , this is tiresome if you do it by yourself. So you should use a plugin like [Prettier]( https://prettier.io/) to format the code.

**Comment by vikasjangir202** [comment]
I have already installed prettier extension but i don`t think it`s working properly. For now i have updated the files manually but will check out what is wrong with the extension.

**Comment by ajay47** [comment]
If you are using VS code you can configure the formatter by pressing , Ctrl + Shift + P, it will open global search, type format and you will see the option to **format document with** select it and you will see pretteir there as option if the extension is installed.
